import api from './api';

// Types
export enum DisclosureType {
  CONSOLIDATION_SCOPE = 'consolidation_scope',
  CONSOLIDATION_METHODS = 'consolidation_methods',
  ACCOUNTING_POLICIES = 'accounting_policies',
  GOODWILL = 'goodwill',
  MINORITY_INTERESTS = 'minority_interests',
  INTERCOMPANY_TRANSACTIONS = 'intercompany_transactions',
  CURRENCY_TRANSLATION = 'currency_translation',
  DEFERRED_TAXES = 'deferred_taxes',
  CONTINGENT_LIABILITIES = 'contingent_liabilities',
  EMPLOYEES = 'employees',
  BOARD_COMPENSATION = 'board_compensation',
  SIGNIFICANT_EVENTS = 'significant_events',
  SUBSEQUENT_EVENTS = 'subsequent_events',
  RELATED_PARTIES = 'related_parties',
  SEGMENT_REPORTING = 'segment_reporting',
}

export enum NoteSectionStatus {
  DRAFT = 'draft',
  REVIEW_PENDING = 'review_pending',
  REVIEWED = 'reviewed',
  FINALIZED = 'finalized',
  SUPERSEDED = 'superseded',
}

export enum ExportFormat {
  JSON = 'json',
  TEXT = 'text',
  MARKDOWN = 'markdown',
  HTML = 'html',
  PDF = 'pdf',
  WORD_DOCX = 'word_docx',
  XBRL = 'xbrl',
}

export interface KonzernanhangDocument {
  id: string;
  financialStatementId: string;
  version: number;
  isCurrent: boolean;
  fiscalYear: number;
  periodStart: string;
  periodEnd: string;
  documentTitle: string;
  status: NoteSectionStatus;
  totalSections: number;
  completedSections: number;
  generatedAt: string;
  generatedByUserId: string | null;
  generatedByName: string | null;
  reviewedByUserId: string | null;
  reviewedByName: string | null;
  reviewedAt: string | null;
  reviewNotes: string | null;
  approvedByUserId: string | null;
  approvedByName: string | null;
  approvedAt: string | null;
  approvalNotes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface KonzernanhangSection {
  id: string;
  documentId: string;
  disclosureType: DisclosureType;
  sectionNumber: string;
  sectionTitle: string;
  hgbSection: string | null;
  isMandatory: boolean;
  contentText: string | null;
  contentJson: any;
  contentHtml: string | null;
  isAutoGenerated: boolean;
  autoGenerationSource: string | null;
  manualOverride: boolean;
  status: NoteSectionStatus;
  hasChangesFromPriorYear: boolean;
  priorYearComparison: string | null;
  displayOrder: number;
  preparedByUserId: string | null;
  preparedByName: string | null;
  preparedAt: string;
  reviewedByUserId: string | null;
  reviewedByName: string | null;
  reviewedAt: string | null;
  reviewNotes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ExportMetadata {
  id: string;
  documentId: string;
  format: ExportFormat;
  fileName: string;
  fileSize: number;
  contentHash: string;
  exportedByUserId: string | null;
  exportedByName: string | null;
  exportedAt: string;
  exportPurpose: string | null;
  recipient: string | null;
}

export interface DisclosureTypeInfo {
  type: DisclosureType;
  label: string;
  hgbSection: string;
}

export interface ExportFormatInfo {
  format: ExportFormat;
  label: string;
  available: boolean;
}

export const konzernanhangService = {
  // Document operations
  async createDocument(financialStatementId: string, options?: {
    generatedByUserId?: string;
    generatedByName?: string;
  }): Promise<KonzernanhangDocument> {
    const response = await api.post('/konzernanhang/documents', {
      financialStatementId,
      ...options,
    });
    return response.data;
  },

  async getDocument(id: string): Promise<KonzernanhangDocument> {
    const response = await api.get(`/konzernanhang/documents/${id}`);
    return response.data;
  },

  async getCurrentDocument(financialStatementId: string): Promise<KonzernanhangDocument | null> {
    try {
      const response = await api.get(`/konzernanhang/documents/financial-statement/${financialStatementId}`);
      return response.data;
    } catch (error) {
      return null;
    }
  },

  async reviewDocument(id: string, reviewedByUserId: string, reviewedByName: string, reviewNotes?: string): Promise<KonzernanhangDocument> {
    const response = await api.put(`/konzernanhang/documents/${id}/review`, {
      reviewedByUserId,
      reviewedByName,
      reviewNotes,
    });
    return response.data;
  },

  async approveDocument(id: string, approvedByUserId: string, approvedByName: string, approvalNotes?: string): Promise<KonzernanhangDocument> {
    const response = await api.put(`/konzernanhang/documents/${id}/approve`, {
      approvedByUserId,
      approvedByName,
      approvalNotes,
    });
    return response.data;
  },

  // Generate document with all sections
  async createAndGenerate(financialStatementId: string, options?: {
    generatedByUserId?: string;
    generatedByName?: string;
  }): Promise<{ document: KonzernanhangDocument; sections: KonzernanhangSection[] }> {
    const response = await api.post(`/konzernanhang/generate/${financialStatementId}`, options);
    return response.data;
  },

  async generateSections(documentId: string): Promise<KonzernanhangSection[]> {
    const response = await api.post(`/konzernanhang/documents/${documentId}/generate`);
    return response.data;
  },

  // Section operations
  async getSections(documentId: string): Promise<KonzernanhangSection[]> {
    const response = await api.get(`/konzernanhang/documents/${documentId}/sections`);
    return response.data;
  },

  async createSection(section: Partial<KonzernanhangSection>): Promise<KonzernanhangSection> {
    const response = await api.post('/konzernanhang/sections', section);
    return response.data;
  },

  async updateSection(id: string, updates: Partial<KonzernanhangSection>): Promise<KonzernanhangSection> {
    const response = await api.put(`/konzernanhang/sections/${id}`, updates);
    return response.data;
  },

  async deleteSection(id: string): Promise<void> {
    await api.delete(`/konzernanhang/sections/${id}`);
  },

  async reviewSection(id: string, reviewedByUserId: string, reviewedByName: string, reviewNotes?: string): Promise<KonzernanhangSection> {
    const response = await api.put(`/konzernanhang/sections/${id}/review`, {
      reviewedByUserId,
      reviewedByName,
      reviewNotes,
    });
    return response.data;
  },

  // Export operations
  async exportDocument(documentId: string, format: ExportFormat): Promise<Blob> {
    const response = await api.get(`/konzernanhang/documents/${documentId}/export/${format}`, {
      responseType: 'blob',
    });
    return response.data;
  },

  async getExportHistory(documentId: string): Promise<ExportMetadata[]> {
    const response = await api.get(`/konzernanhang/documents/${documentId}/exports`);
    return response.data;
  },

  // Utility
  async getDisclosureTypes(): Promise<DisclosureTypeInfo[]> {
    const response = await api.get('/konzernanhang/disclosure-types');
    return response.data;
  },

  async getExportFormats(): Promise<ExportFormatInfo[]> {
    const response = await api.get('/konzernanhang/export-formats');
    return response.data;
  },
};

export default konzernanhangService;
